name: Pre-commit
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  precommit:
    runs-on: ubuntu-latest
    container:
      # https://github.com/larsks/opf-go-precommit
      image: quay.io/larsks/opf-go-precommit:d3dc2d2
      env:
        XDG_CACHE_HOME: /cache
        GOCACHE: /cache/go-build
        GOMODCACHE: /cache/go-mod
        PRE_COMMIT_HOME: /cache/pre-commit
      volumes:
        - /cache
    steps:
      - uses: actions/checkout@v2

      - name: Activate cache
        uses: actions/cache@v2
        with:
          path: /cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/go.sum', '.pre-commit-config.yaml') }}

      - name: Run pre-commit checks
        run: pre-commit run --all-files
